insert into job (id, name, group_id, address_id) values (1, 'GIS Technical Architect', 9, 6600);
insert into job (id, name, group_id, address_id) values (2, 'Internal Auditor', 5, 120);
insert into job (id, name, group_id, address_id) values (3, 'Senior Cost Accountant', 4, 345);
insert into job (id, name, group_id, address_id) values (4, 'Environmental Tech', 17, 555);
insert into job (id, name, group_id, address_id) values (5, 'Recruiter', 3, 10239);
insert into job (id, name, group_id, address_id) values (6, 'Research Assistant I', 3, 10937);
insert into job (id, name, group_id, address_id) values (7, 'Administrative Officer', 2, 1694);
insert into job (id, name, group_id, address_id) values (8, 'Senior Developer', 13, 2110);
insert into job (id, name, group_id, address_id) values (9, 'Safety Technician IV', 26, 3609);
insert into job (id, name, group_id, address_id) values (10, 'GIS Technical Architect', 9, 2289);
insert into job (id, name, group_id, address_id) values (11, 'General Manager', 1, 1211);
insert into job (id, name, group_id, address_id) values (12, 'Assistant Professor', 3, 3089);
insert into job (id, name, group_id, address_id) values (13, 'Electrical Engineer', 9, 505);
insert into job (id, name, group_id, address_id) values (14, 'Senior Cost Accountant', 4, 1080);
insert into job (id, name, group_id, address_id) values (15, 'Nurse Practicioner', 16, 634);
insert into job (id, name, group_id, address_id) values (16, 'Executive Secretary', 4, 1007);
insert into job (id, name, group_id, address_id) values (17, 'Health Coach II', 18, 8568);
insert into job (id, name, group_id, address_id) values (18, 'Speech Pathologist', 16, 6878);
insert into job (id, name, group_id, address_id) values (19, 'Electrical Engineer', 9, 400);
insert into job (id, name, group_id, address_id) values (20, 'Nurse Practicioner', 16, 10703);
insert into job (id, name, group_id, address_id) values (21, 'Environmental Specialist', 20, 7991);
insert into job (id, name, group_id, address_id) values (22, 'Budget/Accounting Analyst III', 6, 1397);
insert into job (id, name, group_id, address_id) values (23, 'Assistant Manager', 4, 1431);
insert into job (id, name, group_id, address_id) values (24, 'Quality Control Specialist', 9, 17184);
insert into job (id, name, group_id, address_id) values (25, 'Technical Writer', 8, 10470);
insert into job (id, name, group_id, address_id) values (26, 'Pharmacist', 18, 8395);
insert into job (id, name, group_id, address_id) values (27, 'VP Quality Control', 24, 40650);
insert into job (id, name, group_id, address_id) values (28, 'Account Executive', 6, 12563);
insert into job (id, name, group_id, address_id) values (29, 'Pharmacist', 18, 24965);
insert into job (id, name, group_id, address_id) values (30, 'Programmer I', 13, 7051);
insert into job (id, name, group_id, address_id) values (31, 'Computer Systems Analyst III', 13, 9718);
insert into job (id, name, group_id, address_id) values (32, 'Nuclear Power Engineer', 9, 6976);
insert into job (id, name, group_id, address_id) values (33, 'Financial Analyst', 4, 3752);
insert into job (id, name, group_id, address_id) values (34, 'Administrative Assistant I', 3, 5191);
insert into job (id, name, group_id, address_id) values (35, 'Quality Engineer', 9, 46862);
insert into job (id, name, group_id, address_id) values (36, 'Office Assistant I', 3, 18033);
insert into job (id, name, group_id, address_id) values (37, 'Assistant Professor', 3, 6309);
insert into job (id, name, group_id, address_id) values (38, 'Administrative Assistant II', 3, 9360);
insert into job (id, name, group_id, address_id) values (39, 'Assistant Manager', 3, 3736);
insert into job (id, name, group_id, address_id) values (40, 'Civil Engineer', 9, 1354);
insert into job (id, name, group_id, address_id) values (41, 'Account Coordinator', 2, 188);
insert into job (id, name, group_id, address_id) values (42, 'General Manager', 1, 5687);
insert into job (id, name, group_id, address_id) values (43, 'Junior Executive', 4, 1447);
insert into job (id, name, group_id, address_id) values (44, 'Chemical Engineer', 9, 532);
insert into job (id, name, group_id, address_id) values (45, 'VP Marketing', 8, 1163);
insert into job (id, name, group_id, address_id) values (46, 'Professor', 20, 648);
insert into job (id, name, group_id, address_id) values (47, 'Operator', 25, 8723);
insert into job (id, name, group_id, address_id) values (48, 'Nuclear Power Engineer', 9, 699);
insert into job (id, name, group_id, address_id) values (49, 'Web Developer II', 9, 919);
insert into job (id, name, group_id, address_id) values (50, 'Web Developer III', 9, 11700);
insert into job (id, name, group_id, address_id) values (51, 'Geologist I', 20, 4777);
insert into job (id, name, group_id, address_id) values (52, 'Desktop Support Technician', 9, 12715);
insert into job (id, name, group_id, address_id) values (53, 'Registered Nurse', 16, 1238);
insert into job (id, name, group_id, address_id) values (54, 'Nurse Practicioner', 16, 14684);
insert into job (id, name, group_id, address_id) values (55, 'Programmer III', 9, 7641);
insert into job (id, name, group_id, address_id) values (56, 'Paralegal', 14, 570);
insert into job (id, name, group_id, address_id) values (57, 'Product Engineer', 9, 30081);
insert into job (id, name, group_id, address_id) values (58, 'Community Outreach Specialist', 7, 12288);
insert into job (id, name, group_id, address_id) values (59, 'VP Accounting', 6, 27911);
insert into job (id, name, group_id, address_id) values (60, 'Assistant Media Planner', 8, 5272);
insert into job (id, name, group_id, address_id) values (61, 'Project Manager', 2, 8787);
insert into job (id, name, group_id, address_id) values (62, 'Librarian', 24, 7162);
insert into job (id, name, group_id, address_id) values (63, 'Social Worker', 24, 8633);
insert into job (id, name, group_id, address_id) values (64, 'Pharmacist', 18, 6774);
insert into job (id, name, group_id, address_id) values (65, 'VP Quality Control', 24, 8105);
insert into job (id, name, group_id, address_id) values (66, 'Clinical Specialist', 18, 8552);
insert into job (id, name, group_id, address_id) values (67, 'Business Systems Development Analyst', 13, 4333);
insert into job (id, name, group_id, address_id) values (68, 'Senior Editor', 8, 611);
insert into job (id, name, group_id, address_id) values (69, 'Marketing Assistant', 8, 5037);
insert into job (id, name, group_id, address_id) values (70, 'Analog Circuit Design manager', 9, 5323);
insert into job (id, name, group_id, address_id) values (71, 'Actuary', 20, 4835);
insert into job (id, name, group_id, address_id) values (72, 'Systems Administrator IV', 2, 9462);
insert into job (id, name, group_id, address_id) values (73, 'Nurse', 16, 7455);
insert into job (id, name, group_id, address_id) values (74, 'Human Resources Manager', 10, 8306);
insert into job (id, name, group_id, address_id) values (75, 'Environmental Tech', 17, 2089);
insert into job (id, name, group_id, address_id) values (76, 'Tax Accountant', 22, 9498);
insert into job (id, name, group_id, address_id) values (77, 'Marketing Manager', 8, 1108);
insert into job (id, name, group_id, address_id) values (78, 'Speech Pathologist', 16, 586);
insert into job (id, name, group_id, address_id) values (79, 'Paralegal', 14, 818);
insert into job (id, name, group_id, address_id) values (80, 'Office Assistant II', 3, 4982);
insert into job (id, name, group_id, address_id) values (81, 'Speech Pathologist', 16, 7047);
insert into job (id, name, group_id, address_id) values (82, 'Accounting Assistant III', 3, 1740);
insert into job (id, name, group_id, address_id) values (83, 'Graphic Designer', 27, 6601);
insert into job (id, name, group_id, address_id) values (84, 'Administrative Officer', 4, 383);
insert into job (id, name, group_id, address_id) values (85, 'Actuary', 20, 1758);
insert into job (id, name, group_id, address_id) values (86, 'Civil Engineer', 9, 860);
insert into job (id, name, group_id, address_id) values (87, 'Structural Analysis Engineer', 9, 26811);
insert into job (id, name, group_id, address_id) values (88, 'Software Test Engineer III', 13, 0852);
insert into job (id, name, group_id, address_id) values (89, 'Food Chemist', 20, 5987);
insert into job (id, name, group_id, address_id) values (90, 'Geological Engineer', 9, 19382);
insert into job (id, name, group_id, address_id) values (91, 'Director of Sales', 8, 2287);
insert into job (id, name, group_id, address_id) values (92, 'Technical Writer', 8, 3625);
insert into job (id, name, group_id, address_id) values (93, 'Project Manager', 2, 8937);
insert into job (id, name, group_id, address_id) values (94, 'Chemical Engineer', 9, 1977);
insert into job (id, name, group_id, address_id) values (95, 'Director of Sales', 8, 982);
insert into job (id, name, group_id, address_id) values (96, 'Developer II', 13, 7423);
insert into job (id, name, group_id, address_id) values (97, 'Financial Advisor', 15, 3171);
insert into job (id, name, group_id, address_id) values (98, 'Senior Developer', 13, 6676);
insert into job (id, name, group_id, address_id) values (99, 'Compensation Analyst', 24, 6172);
insert into job (id, name, group_id, address_id) values (100, 'Executive Secretary', 1, 1405);