insert into job_group (id, name) values (1, 'Office and Clerical');
insert into job_group (id, name) values (2, 'Officials and Administrators');
insert into job_group (id, name) values (3, 'Paraprofessionals');
insert into job_group (id, name) values (4, 'Administrative Professionals');
insert into job_group (id, name) values (5, 'Auditor');
insert into job_group (id, name) values (6, 'Budget and Accounting');
insert into job_group (id, name) values (7, 'Claims Adjudicator');
insert into job_group (id, name) values (8, 'Communications and Marketing');
insert into job_group (id, name) values (9, 'Engineering');
insert into job_group (id, name) values (10, 'Human Resources');
insert into job_group (id, name) values (11, 'Insurance Business Services');
insert into job_group (id, name) values (12, 'Investigator');
insert into job_group (id, name) values (13, 'IT');
insert into job_group (id, name) values (14, 'Legal');
insert into job_group (id, name) values (15, 'Licensing and Regulation');
insert into job_group (id, name, vaccinated_on_job) values (16, 'Medical', true);
insert into job_group (id, name) values (17, 'Natural Resources');
insert into job_group (id, name, vaccinated_on_job) values (18, 'Public Health', true);
insert into job_group (id, name, vaccinated_on_job) values (19, 'Safety', true);
insert into job_group (id, name) values (20, 'Science');
insert into job_group (id, name) values (21, 'Social Services');
insert into job_group (id, name) values (22, 'Tax Professional');
insert into job_group (id, name) values (23, 'Protective Service Workers');
insert into job_group (id, name) values (24, 'Service-Maintenance');
insert into job_group (id, name) values (25, 'Skilled Craft Workers');
insert into job_group (id, name) values (26, 'Technicians');
insert into job_group (id, name) values (27, 'Artists');

