insert into pathology (id, scientific_name, common_name) values (1, 'Acinetobacter baumannii', 'Acinetobacter infections');
insert into pathology (id, scientific_name, common_name) values (2, 'Actinomyces israelii & Actinomyces gerencseriae and Propionibacterium propionicus', 'Actinomycosis');
insert into pathology (id, scientific_name, common_name) values (3, 'Trypanosoma brucei', 'African sleeping sickness (African trypanosomiasis)');
insert into pathology (id, scientific_name, common_name) values (4, 'HIV (Human immunodeficiency virus)', 'AIDS (acquired immunodeficiency syndrome)');
insert into pathology (id, scientific_name, common_name) values (5, 'Entamoeba histolytica', 'Amoebiasis');
insert into pathology (id, scientific_name, common_name) values (6, 'Anaplasma species', 'Anaplasmosis');
insert into pathology (id, scientific_name, common_name) values (7, 'Angiostrongylus', 'Angiostrongyliasis');
insert into pathology (id, scientific_name, common_name) values (8, 'Anisakis', 'Anisakiasis');
insert into pathology (id, scientific_name, common_name) values (9, 'Bacillus anthracis', 'Anthrax');
insert into pathology (id, scientific_name, common_name) values (10, 'Arcanobacterium haemolyticum', 'Arcanobacterium haemolyticum infection');
insert into pathology (id, scientific_name, common_name) values (11, 'Junin virus', 'Argentine hemorrhagic fever');
insert into pathology (id, scientific_name, common_name) values (12, 'Ascaris lumbricoides', 'Ascariasis');
insert into pathology (id, scientific_name, common_name) values (13, 'Aspergillus species', 'Aspergillosis');
insert into pathology (id, scientific_name, common_name) values (14, 'Astroviridae species', 'Astrovirus infection');
insert into pathology (id, scientific_name, common_name) values (15, 'Babesia species', 'Babesiosis');
insert into pathology (id, scientific_name, common_name) values (16, 'Bacillus cereus', 'Bacillus cereus infection');
insert into pathology (id, scientific_name, common_name) values (17, 'Multiple meningitis bacteria', 'Bacterial meningitis');
insert into pathology (id, scientific_name, common_name) values (18, 'Multiple pneumonia bacteria', 'Bacterial pneumonia');
insert into pathology (id, scientific_name, common_name) values (19, 'List of bacterial vaginosis microbiota', 'Bacterial vaginosis');
insert into pathology (id, scientific_name, common_name) values (20, 'Bacteroides species', 'Bacteroides infection');
insert into pathology (id, scientific_name, common_name) values (21, 'Balantidium coli', 'Balantidiasis');
insert into pathology (id, scientific_name, common_name) values (22, 'Bartonella', 'Bartonellosis');
insert into pathology (id, scientific_name, common_name) values (23, 'Baylisascaris species', 'Baylisascaris infection');
insert into pathology (id, scientific_name, common_name) values (24, 'BK virus', 'BK virus infection');
insert into pathology (id, scientific_name, common_name) values (25, 'Piedraia hortae', 'Black piedra');
insert into pathology (id, scientific_name, common_name) values (26, 'Blastocystis species', 'Blastocystosis');
insert into pathology (id, scientific_name, common_name) values (27, 'Blastomyces dermatitidis', 'Blastomycosis');
insert into pathology (id, scientific_name, common_name) values (28, 'Machupo virus', 'Bolivian hemorrhagic fever');
insert into pathology (id, scientific_name, common_name) values (29, 'Clostridium botulinum; Note: Botulism is not an infection by Clostridium botulinum but caused by the intake of botulinum toxin.', 'Botulism (and Infant botulism)');
insert into pathology (id, scientific_name, common_name) values (30, 'Sabiá virus', 'Brazilian hemorrhagic fever');
insert into pathology (id, scientific_name, common_name) values (31, 'Brucella species', 'Brucellosis');
insert into pathology (id, scientific_name, common_name) values (32, 'Yersinia pestis', 'Bubonic plague');
insert into pathology (id, scientific_name, common_name) values (33, 'usually Burkholderia cepacia and other Burkholderia species', 'Burkholderia infection');
insert into pathology (id, scientific_name, common_name) values (34, 'Mycobacterium ulcerans', 'Buruli ulcer');
insert into pathology (id, scientific_name, common_name) values (35, 'Caliciviridae species', 'Calicivirus infection (Norovirus and Sapovirus)');
insert into pathology (id, scientific_name, common_name) values (36, 'Campylobacter species', 'Campylobacteriosis');
insert into pathology (id, scientific_name, common_name) values (37, 'usually Candida albicans and other Candida species', 'Candidiasis (Moniliasis; Thrush)');
insert into pathology (id, scientific_name, common_name) values (38, 'Intestinal disease by Capillaria philippinensis & hepatic disease by Capillaria hepatica and pulmonary disease by Capillaria aerophila', 'Capillariasis');
insert into pathology (id, scientific_name, common_name) values (39, 'Bartonella bacilliformis', 'Carrion''s disease');
insert into pathology (id, scientific_name, common_name) values (40, 'Bartonella henselae', 'Cat-scratch disease');
insert into pathology (id, scientific_name, common_name) values (41, 'usually Group A Streptococcus and Staphylococcus', 'Cellulitis');
insert into pathology (id, scientific_name, common_name) values (42, 'Trypanosoma cruzi', 'Chagas disease (American trypanosomiasis)');
insert into pathology (id, scientific_name, common_name) values (43, 'Haemophilus ducreyi', 'Chancroid');
insert into pathology (id, scientific_name, common_name) values (44, 'Varicella zoster virus (VZV)', 'Chickenpox');
insert into pathology (id, scientific_name, common_name) values (45, 'Alphavirus', 'Chikungunya');
insert into pathology (id, scientific_name, common_name) values (46, 'Chlamydia trachomatis', 'Chlamydia');
insert into pathology (id, scientific_name, common_name) values (47, 'Chlamydophila pneumoniae', 'Chlamydophila pneumoniae infection (Taiwan acute respiratory agent or TWAR)');
insert into pathology (id, scientific_name, common_name) values (48, 'Vibrio cholerae', 'Cholera');
insert into pathology (id, scientific_name, common_name) values (49, 'usually Fonsecaea pedrosoi', 'Chromoblastomycosis');
insert into pathology (id, scientific_name, common_name) values (50, 'Batrachochytrium dendrabatidis', 'Chytridiomycosis');
insert into pathology (id, scientific_name, common_name) values (51, 'Clonorchis sinensis', 'Clonorchiasis');
insert into pathology (id, scientific_name, common_name) values (52, 'Clostridium difficile', 'Clostridium difficile colitis');
insert into pathology (id, scientific_name, common_name) values (53, 'Coccidioides immitis and Coccidioides posadasii', 'Coccidioidomycosis');
insert into pathology (id, scientific_name, common_name) values (54, 'Colorado tick fever virus (CTFV)', 'Colorado tick fever (CTF)');
insert into pathology (id, scientific_name, common_name) values (55, 'usually rhinoviruses and coronaviruses', 'Common cold (Acute viral rhinopharyngitis; Acute coryza)');
insert into pathology (id, scientific_name, common_name) values (56, 'Severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2)', 'Coronavirus disease 2019 (COVID-19)');
insert into pathology (id, scientific_name, common_name) values (57, 'PRNP', 'Creutzfeldt–Jakob disease (CJD)');
insert into pathology (id, scientific_name, common_name) values (58, 'Crimean-Congo hemorrhagic fever virus', 'Crimean-Congo hemorrhagic fever (CCHF)');
insert into pathology (id, scientific_name, common_name) values (59, 'Cryptococcus neoformans', 'Cryptococcosis');
insert into pathology (id, scientific_name, common_name) values (60, 'Cryptosporidium species', 'Cryptosporidiosis');
insert into pathology (id, scientific_name, common_name) values (61, 'usually Ancylostoma braziliense; multiple other parasites', 'Cutaneous larva migrans (CLM)');
insert into pathology (id, scientific_name, common_name) values (62, 'Cyclospora cayetanensis', 'Cyclosporiasis');
insert into pathology (id, scientific_name, common_name) values (63, 'Taenia solium', 'Cysticercosis');
insert into pathology (id, scientific_name, common_name) values (64, 'Cytomegalovirus', 'Cytomegalovirus infection');
insert into pathology (id, scientific_name, common_name) values (65, 'Dengue viruses (DEN-1 & DEN-2 & DEN-3 and DEN-4) – Flaviviruses', 'Dengue fever');
insert into pathology (id, scientific_name, common_name) values (66, 'Green algae Desmodesmus armatus', 'Desmodesmus infection');
insert into pathology (id, scientific_name, common_name) values (67, 'Dientamoeba fragilis', 'Dientamoebiasis');
insert into pathology (id, scientific_name, common_name) values (68, 'Corynebacterium diphtheriae', 'Diphtheria');
insert into pathology (id, scientific_name, common_name) values (69, 'Diphyllobothrium', 'Diphyllobothriasis');
insert into pathology (id, scientific_name, common_name) values (70, 'Dracunculus medinensis', 'Dracunculiasis');
insert into pathology (id, scientific_name, common_name) values (71, 'Ebolavirus (EBOV)', 'Ebola hemorrhagic fever');
insert into pathology (id, scientific_name, common_name) values (72, 'Echinococcus species', 'Echinococcosis');
insert into pathology (id, scientific_name, common_name) values (73, 'Ehrlichia species', 'Ehrlichiosis');
insert into pathology (id, scientific_name, common_name) values (74, 'Enterobius vermicularis', 'Enterobiasis (Pinworm infection)');
insert into pathology (id, scientific_name, common_name) values (75, 'Enterococcus species', 'Enterococcus infection');
insert into pathology (id, scientific_name, common_name) values (76, 'Enterovirus species', 'Enterovirus infection');
insert into pathology (id, scientific_name, common_name) values (77, 'Rickettsia prowazekii', 'Epidemic typhus');
insert into pathology (id, scientific_name, common_name) values (78, 'Parvovirus B19', 'Erythema infectiosum (Fifth disease)');
insert into pathology (id, scientific_name, common_name) values (79, 'Human herpesvirus 6 (HHV-6) and human herpesvirus 7 (HHV-7)', 'Exanthem subitum (Sixth disease)');
insert into pathology (id, scientific_name, common_name) values (80, 'Fasciola hepatica and Fasciola gigantica', 'Fasciolasis');
insert into pathology (id, scientific_name, common_name) values (81, 'Fasciolopsis buski', 'Fasciolopsiasis');
insert into pathology (id, scientific_name, common_name) values (82, 'PRNP insomnia', 'Fatal familial insomnia (FFI)');
insert into pathology (id, scientific_name, common_name) values (83, 'Filarioidea superfamily', 'Filariasis');
insert into pathology (id, scientific_name, common_name) values (84, 'Clostridium perfringens', 'Food poisoning by Clostridium perfringens');
insert into pathology (id, scientific_name, common_name) values (85, 'multiple', 'Free-living amebic infection');
insert into pathology (id, scientific_name, common_name) values (86, 'Fusobacterium species', 'Fusobacterium infection');
insert into pathology (id, scientific_name, common_name) values (87, 'usually Clostridium perfringens; other Clostridium species', 'Gas gangrene (Clostridial myonecrosis)');
insert into pathology (id, scientific_name, common_name) values (88, 'Geotrichum candidum', 'Geotrichosis');
insert into pathology (id, scientific_name, common_name) values (89, 'PRNP Gerstmann-Sträussler-Scheinker', 'Gerstmann-Sträussler-Scheinker syndrome (GSS)');
insert into pathology (id, scientific_name, common_name) values (90, 'Giardia lamblia', 'Giardiasis');
insert into pathology (id, scientific_name, common_name) values (91, 'Burkholderia mallei', 'Glanders');
insert into pathology (id, scientific_name, common_name) values (92, 'Gnathostoma spinigerum and Gnathostoma hispidum', 'Gnathostomiasis');
insert into pathology (id, scientific_name, common_name) values (93, 'Neisseria gonorrhoeae', 'Gonorrhea');
insert into pathology (id, scientific_name, common_name) values (94, 'Klebsiella granulomatis', 'Granuloma inguinale (Donovanosis)');
insert into pathology (id, scientific_name, common_name) values (95, 'Streptococcus pyogenes', 'Group A streptococcal infection');
insert into pathology (id, scientific_name, common_name) values (96, 'Streptococcus agalactiae', 'Group B streptococcal infection');
insert into pathology (id, scientific_name, common_name) values (97, 'Haemophilus influenzae', 'Haemophilus influenzae infection');
insert into pathology (id, scientific_name, common_name) values (98, 'Enteroviruses & mainly Coxsackie A virus and enterovirus 71 (EV71)', 'Hand & foot and mouth disease (HFMD)');
insert into pathology (id, scientific_name, common_name) values (99, 'Sin Nombre virus', 'Hantavirus Pulmonary Syndrome (HPS)');
insert into pathology (id, scientific_name, common_name) values (100, 'Heartland virus', 'Heartland virus disease');
insert into pathology (id, scientific_name, common_name) values (101, 'Helicobacter pylori', 'Helicobacter pylori infection');
insert into pathology (id, scientific_name, common_name) values (102, 'Escherichia coli O157:H7 & O111 and O104:H4', 'Hemolytic-uremic syndrome (HUS)');
insert into pathology (id, scientific_name, common_name) values (103, 'Bunyaviridae species', 'Hemorrhagic fever with renal syndrome (HFRS)');
insert into pathology (id, scientific_name, common_name) values (104, 'Hendra virus', 'Hendra virus infection');
insert into pathology (id, scientific_name, common_name) values (105, 'Hepatitis A virus', 'Hepatitis A');
insert into pathology (id, scientific_name, common_name) values (106, 'Hepatitis B virus', 'Hepatitis B');
insert into pathology (id, scientific_name, common_name) values (107, 'Hepatitis C virus', 'Hepatitis C');
insert into pathology (id, scientific_name, common_name) values (108, 'Hepatitis D Virus', 'Hepatitis D');
insert into pathology (id, scientific_name, common_name) values (109, 'Hepatitis E virus', 'Hepatitis E');
insert into pathology (id, scientific_name, common_name) values (110, 'Herpes simplex virus 1 and 2 (HSV-1 and HSV-2)', 'Herpes simplex');
insert into pathology (id, scientific_name, common_name) values (111, 'Histoplasma capsulatum', 'Histoplasmosis');
insert into pathology (id, scientific_name, common_name) values (112, 'Ancylostoma duodenale and Necator americanus', 'Hookworm infection');
insert into pathology (id, scientific_name, common_name) values (113, 'Human bocavirus (HBoV)', 'Human bocavirus infection');
insert into pathology (id, scientific_name, common_name) values (114, 'Ehrlichia ewingii', 'Human ewingii ehrlichiosis');
insert into pathology (id, scientific_name, common_name) values (115, 'Anaplasma phagocytophilum', 'Human granulocytic anaplasmosis (HGA)');
insert into pathology (id, scientific_name, common_name) values (116, 'Human metapneumovirus (hMPV)', 'Human metapneumovirus infection');
insert into pathology (id, scientific_name, common_name) values (117, 'Ehrlichia chaffeensis', 'Human monocytic ehrlichiosis');
insert into pathology (id, scientific_name, common_name) values (118, 'One of the human papillomaviruses', 'Human papillomavirus (HPV) infection');
insert into pathology (id, scientific_name, common_name) values (119, 'Human parainfluenza viruses (HPIV)', 'Human parainfluenza virus infection');
insert into pathology (id, scientific_name, common_name) values (120, 'Hymenolepis nana and Hymenolepis diminuta', 'Hymenolepiasis');
insert into pathology (id, scientific_name, common_name) values (121, 'Epstein–Barr virus (EBV)', 'Epstein–Barr virus infectious mononucleosis (Mono)');
insert into pathology (id, scientific_name, common_name) values (122, 'Orthomyxoviridae species', 'Influenza (flu)');
insert into pathology (id, scientific_name, common_name) values (123, 'Isospora belli', 'Isosporiasis');
insert into pathology (id, scientific_name, common_name) values (124, 'unknown; evidence supports that it is infectious', 'Kawasaki disease');
insert into pathology (id, scientific_name, common_name) values (125, 'Multiple keratitis', 'Keratitis');
insert into pathology (id, scientific_name, common_name) values (126, 'Kingella kingae', 'Kingella kingae infection');
insert into pathology (id, scientific_name, common_name) values (127, 'PRNP Kuru', 'Kuru');
insert into pathology (id, scientific_name, common_name) values (128, 'Lassa virus', 'Lassa fever');
insert into pathology (id, scientific_name, common_name) values (129, 'Legionella pneumophila', 'Legionellosis (Legionnaires'' disease)');
insert into pathology (id, scientific_name, common_name) values (130, 'Legionella pneumophila fever', 'Pontiac fever');
insert into pathology (id, scientific_name, common_name) values (131, 'Leishmania species', 'Leishmaniasis');
insert into pathology (id, scientific_name, common_name) values (132, 'Mycobacterium leprae and Mycobacterium lepromatosis', 'Leprosy');
insert into pathology (id, scientific_name, common_name) values (133, 'Leptospira species', 'Leptospirosis');
insert into pathology (id, scientific_name, common_name) values (134, 'Listeria monocytogenes', 'Listeriosis');
insert into pathology (id, scientific_name, common_name) values (135, 'Borrelia burgdorferi & Borrelia garinii & and Borrelia afzelii', 'Lyme disease (Lyme borreliosis)');
insert into pathology (id, scientific_name, common_name) values (136, 'Wuchereria bancrofti and Brugia malayi', 'Lymphatic filariasis (Elephantiasis)');
insert into pathology (id, scientific_name, common_name) values (137, 'Lymphocytic choriomeningitis virus (LCMV)', 'Lymphocytic choriomeningitis');
insert into pathology (id, scientific_name, common_name) values (138, 'Plasmodium species', 'Malaria');
insert into pathology (id, scientific_name, common_name) values (139, 'Marburg virus', 'Marburg hemorrhagic fever (MHF)');
insert into pathology (id, scientific_name, common_name) values (140, 'Measles virus', 'Measles');
insert into pathology (id, scientific_name, common_name) values (141, 'Middle East respiratory syndrome coronavirus', 'Middle East respiratory syndrome (MERS)');
insert into pathology (id, scientific_name, common_name) values (142, 'Burkholderia pseudomallei', 'Melioidosis (Whitmore''s disease)');
insert into pathology (id, scientific_name, common_name) values (143, 'Multiple Meningitis', 'Meningitis');
insert into pathology (id, scientific_name, common_name) values (144, 'Neisseria meningitidis', 'Meningococcal disease');
insert into pathology (id, scientific_name, common_name) values (145, 'usually Metagonimus yokagawai', 'Metagonimiasis');
insert into pathology (id, scientific_name, common_name) values (146, 'Microsporidia phylum', 'Microsporidiosis');
insert into pathology (id, scientific_name, common_name) values (147, 'Molluscum contagiosum virus (MCV)', 'Molluscum contagiosum (MC)');
insert into pathology (id, scientific_name, common_name) values (148, 'Monkeypox virus', 'Monkeypox');
insert into pathology (id, scientific_name, common_name) values (149, 'Mumps virus', 'Mumps');
insert into pathology (id, scientific_name, common_name) values (150, 'Rickettsia typhi', 'Murine typhus (Endemic typhus)');
insert into pathology (id, scientific_name, common_name) values (151, 'Mycoplasma pneumoniae', 'Mycoplasma pneumonia');
insert into pathology (id, scientific_name, common_name) values (152, 'Mycoplasma genitalium', 'Mycoplasma genitalium infection');
insert into pathology (id, scientific_name, common_name) values (153, 'numerous species of bacteria (Actinomycetoma) and fungi (Eumycetoma)', 'Mycetoma');
insert into pathology (id, scientific_name, common_name) values (154, 'parasitic dipterous fly larvae', 'Myiasis');
insert into pathology (id, scientific_name, common_name) values (155, 'most commonly Chlamydia trachomatis and Neisseria gonorrhoeae', 'Neonatal conjunctivitis (Ophthalmia neonatorum)');
insert into pathology (id, scientific_name, common_name) values (156, 'Nipah virus', 'Nipah virus infection');
insert into pathology (id, scientific_name, common_name) values (157, 'Norovirus', 'Norovirus');
insert into pathology (id, scientific_name, common_name) values (158, 'PRNP Creutzfeldt–Jakob', '(New) Variant Creutzfeldt–Jakob disease (vCJD & nvCJD)');
insert into pathology (id, scientific_name, common_name) values (159, 'usually Nocardia asteroides and other Nocardia species', 'Nocardiosis');
insert into pathology (id, scientific_name, common_name) values (160, 'Onchocerca volvulus', 'Onchocerciasis (River blindness)');
insert into pathology (id, scientific_name, common_name) values (161, 'Opisthorchis viverrini and Opisthorchis felineus', 'Opisthorchiasis');
insert into pathology (id, scientific_name, common_name) values (162, 'Paracoccidioides brasiliensis', 'Paracoccidioidomycosis (South American blastomycosis)');
insert into pathology (id, scientific_name, common_name) values (163, 'usually Paragonimus westermani and other Paragonimus species', 'Paragonimiasis');
insert into pathology (id, scientific_name, common_name) values (164, 'Pasteurella species', 'Pasteurellosis');
insert into pathology (id, scientific_name, common_name) values (165, 'Pediculus humanus capitis', 'Pediculosis capitis (Head lice)');
insert into pathology (id, scientific_name, common_name) values (166, 'Pediculus humanus corporis', 'Pediculosis corporis (Body lice)');
insert into pathology (id, scientific_name, common_name) values (167, 'Pthirus pubis', 'Pediculosis pubis (pubic lice & crab lice)');
insert into pathology (id, scientific_name, common_name) values (168, 'Multiple PID', 'Pelvic inflammatory disease (PID)');
insert into pathology (id, scientific_name, common_name) values (169, 'Bordetella pertussis', 'Pertussis (whooping cough)');
insert into pathology (id, scientific_name, common_name) values (170, 'Yersinia Pestis Plague', 'Plague');
insert into pathology (id, scientific_name, common_name) values (171, 'Streptococcus pneumoniae', 'Pneumococcal infection');
insert into pathology (id, scientific_name, common_name) values (172, 'Pneumocystis jirovecii', 'Pneumocystis pneumonia (PCP)');
insert into pathology (id, scientific_name, common_name) values (173, 'Multiple Pneumonia', 'Pneumonia');
insert into pathology (id, scientific_name, common_name) values (174, 'Poliovirus', 'Poliomyelitis');
insert into pathology (id, scientific_name, common_name) values (175, 'Prevotella species', 'Prevotella infection');
insert into pathology (id, scientific_name, common_name) values (176, 'usually Naegleria fowleri', 'Primary amoebic meningoencephalitis (PAM)');
insert into pathology (id, scientific_name, common_name) values (177, 'JC virus', 'Progressive multifocal leukoencephalopathy');
insert into pathology (id, scientific_name, common_name) values (178, 'Chlamydophila psittaci', 'Psittacosis');
insert into pathology (id, scientific_name, common_name) values (179, 'Coxiella burnetii', 'Q fever');
insert into pathology (id, scientific_name, common_name) values (180, 'Rabies virus', 'Rabies');
insert into pathology (id, scientific_name, common_name) values (181, 'Borrelia hermsii & Borrelia recurrentis & and other Borrelia species', 'Relapsing fever');
insert into pathology (id, scientific_name, common_name) values (182, 'Respiratory syncytial virus (RSV)', 'Respiratory syncytial virus infection');
insert into pathology (id, scientific_name, common_name) values (183, 'Rhinosporidium seeberi', 'Rhinosporidiosis');
insert into pathology (id, scientific_name, common_name) values (184, 'Rhinovirus', 'Rhinovirus infection');
insert into pathology (id, scientific_name, common_name) values (185, 'Rickettsia species', 'Rickettsial infection');
insert into pathology (id, scientific_name, common_name) values (186, 'Rickettsia akari', 'Rickettsialpox');
insert into pathology (id, scientific_name, common_name) values (187, 'Rift Valley fever virus', 'Rift Valley fever (RVF)');
insert into pathology (id, scientific_name, common_name) values (188, 'Rickettsia rickettsii', 'Rocky Mountain spotted fever (RMSF)');
insert into pathology (id, scientific_name, common_name) values (189, 'Rotavirus', 'Rotavirus infection');
insert into pathology (id, scientific_name, common_name) values (190, 'Rubella virus', 'Rubella');
insert into pathology (id, scientific_name, common_name) values (191, 'Salmonella species', 'Salmonellosis');
insert into pathology (id, scientific_name, common_name) values (192, 'SARS coronavirus', 'Severe acute respiratory syndrome (SARS)');
insert into pathology (id, scientific_name, common_name) values (193, 'Sarcoptes scabiei', 'Scabies');
insert into pathology (id, scientific_name, common_name) values (194, 'Group A Streptococcus species', 'Scarlet fever');
insert into pathology (id, scientific_name, common_name) values (195, 'Schistosoma species', 'Schistosomiasis');
insert into pathology (id, scientific_name, common_name) values (196, 'Multiple Sepsis', 'Sepsis');
insert into pathology (id, scientific_name, common_name) values (197, 'Shigella species', 'Shigellosis (bacillary dysentery)');
insert into pathology (id, scientific_name, common_name) values (198, 'Varicella zoster herpes virus (VZV)', 'Shingles (Herpes zoster)');
insert into pathology (id, scientific_name, common_name) values (199, 'Variola major or Variola minor', 'Smallpox (variola)');
insert into pathology (id, scientific_name, common_name) values (200, 'Sporothrix schenckii', 'Sporotrichosis');
insert into pathology (id, scientific_name, common_name) values (201, 'Staphylococcus food poisoning species', 'Staphylococcal food poisoning');
insert into pathology (id, scientific_name, common_name) values (202, 'Staphylococcus species', 'Staphylococcal infection');
insert into pathology (id, scientific_name, common_name) values (203, 'Strongyloides stercoralis', 'Strongyloidiasis');
insert into pathology (id, scientific_name, common_name) values (204, 'Measles Subacute virus', 'Subacute sclerosing panencephalitis');
insert into pathology (id, scientific_name, common_name) values (205, 'Treponema pallidum', 'Bejel & Syphilis & and Yaws');
insert into pathology (id, scientific_name, common_name) values (206, 'Taenia species', 'Taeniasis');
insert into pathology (id, scientific_name, common_name) values (207, 'Clostridium tetani', 'Tetanus (lockjaw)');
insert into pathology (id, scientific_name, common_name) values (208, 'usually Trichophyton species', 'Tinea barbae (barber''s itch)');
insert into pathology (id, scientific_name, common_name) values (209, 'usually Trichophyton tonsurans', 'Tinea capitis (ringworm of the scalp)');
insert into pathology (id, scientific_name, common_name) values (210, 'usually Trichophyton corporis species', 'Tinea corporis (ringworm of the body)');
insert into pathology (id, scientific_name, common_name) values (211, 'usually Epidermophyton floccosum & Trichophyton rubrum & and Trichophyton mentagrophytes', 'Tinea cruris (Jock itch)');
insert into pathology (id, scientific_name, common_name) values (212, 'Trichophyton rubrum', 'Tinea manum (ringworm of the hand)');
insert into pathology (id, scientific_name, common_name) values (213, 'usually Hortaea werneckii', 'Tinea nigra');
insert into pathology (id, scientific_name, common_name) values (214, 'usually Trichophyton pedis species', 'Tinea pedis (athlete’s foot)');
insert into pathology (id, scientific_name, common_name) values (215, 'usually Trichophyton unguium species', 'Tinea unguium (onychomycosis)');
insert into pathology (id, scientific_name, common_name) values (216, 'Malassezia species', 'Tinea versicolor (Pityriasis versicolor)');
insert into pathology (id, scientific_name, common_name) values (217, 'Staphylococcus aureus or Streptococcus pyogenes', 'Toxic shock syndrome (TSS)');
insert into pathology (id, scientific_name, common_name) values (218, 'Toxocara canis or Toxocara cati', 'Toxocariasis (ocular larva migrans (OLM))');
insert into pathology (id, scientific_name, common_name) values (219, 'Toxocara canis or Toxocara visceral cati', 'Toxocariasis (visceral larva migrans (VLM))');
insert into pathology (id, scientific_name, common_name) values (220, 'Toxoplasma gondii', 'Toxoplasmosis');
insert into pathology (id, scientific_name, common_name) values (221, 'Chlamydia Trachoma trachomatis', 'Trachoma');
insert into pathology (id, scientific_name, common_name) values (222, 'Trichinella spiralis', 'Trichinosis');
insert into pathology (id, scientific_name, common_name) values (223, 'Trichomonas vaginalis', 'Trichomoniasis');
insert into pathology (id, scientific_name, common_name) values (224, 'Trichuris trichiura', 'Trichuriasis (whipworm infection)');
insert into pathology (id, scientific_name, common_name) values (225, 'usually Mycobacterium tuberculosis', 'Tuberculosis');
insert into pathology (id, scientific_name, common_name) values (226, 'Francisella tularensis', 'Tularemia');
insert into pathology (id, scientific_name, common_name) values (227, 'Salmonella enterica subsp. enterica & serovar typhi', 'Typhoid fever');
insert into pathology (id, scientific_name, common_name) values (228, 'Rickettsia', 'Typhus fever');
insert into pathology (id, scientific_name, common_name) values (229, 'Ureaplasma urealyticum', 'Ureaplasma urealyticum infection');
insert into pathology (id, scientific_name, common_name) values (230, 'Coccidioides immitis or Coccidioides posadasii.[1]', 'Valley fever');
insert into pathology (id, scientific_name, common_name) values (231, 'Venezuelan equine encephalitis virus', 'Venezuelan equine encephalitis');
insert into pathology (id, scientific_name, common_name) values (232, 'Guanarito virus', 'Venezuelan hemorrhagic fever');
insert into pathology (id, scientific_name, common_name) values (233, 'Vibrio vulnificus', 'Vibrio vulnificus infection');
insert into pathology (id, scientific_name, common_name) values (234, 'Vibrio parahaemolyticus', 'Vibrio parahaemolyticus enteritis');
insert into pathology (id, scientific_name, common_name) values (235, 'multiple viruses', 'Viral pneumonia');
insert into pathology (id, scientific_name, common_name) values (236, 'West Nile virus', 'West Nile fever');
insert into pathology (id, scientific_name, common_name) values (237, 'Trichosporon beigelii', 'White piedra (tinea blanca)');
insert into pathology (id, scientific_name, common_name) values (238, 'Yersinia pseudotuberculosis', 'Yersinia pseudotuberculosis infection');
insert into pathology (id, scientific_name, common_name) values (239, 'Yersinia enterocolitica', 'Yersiniosis');
insert into pathology (id, scientific_name, common_name) values (240, 'Yellow fever virus', 'Yellow fever');
insert into pathology (id, scientific_name, common_name) values (241, 'Zeaspora fungus', 'Zeaspora');
insert into pathology (id, scientific_name, common_name) values (242, 'Zika virus', 'Zika fever');
insert into pathology (id, scientific_name, common_name) values (243, 'Mucorales order (Mucormycosis) and Entomophthorales order (Entomophthoramycosis)', 'Zygomycosis');
insert into pathology (id, scientific_name, common_name) values (244, 'Adenoviridae', 'Adenovirus');

