insert into county (id, name, district_id) values (1, 'Águeda', 1);
insert into county (id, name, district_id) values (2, 'Albergaria-a-Velha', 1);
insert into county (id, name, district_id) values (3, 'Anadia', 1);
insert into county (id, name, district_id) values (4, 'Arouca', 1);
insert into county (id, name, district_id) values (5, 'Aveiro', 1);
insert into county (id, name, district_id) values (6, 'Castelo de Paiva', 1);
insert into county (id, name, district_id) values (7, 'Espinho', 1);
insert into county (id, name, district_id) values (8, 'Estarreja', 1);
insert into county (id, name, district_id) values (9, 'Santa Maria da Feira', 1);
insert into county (id, name, district_id) values (10, 'Ílhavo', 1);
insert into county (id, name, district_id) values (11, 'Mealhada', 1);
insert into county (id, name, district_id) values (12, 'Murtosa', 1);
insert into county (id, name, district_id) values (13, 'Oliveira de Azeméis', 1);
insert into county (id, name, district_id) values (14, 'Oliveira do Bairro', 1);
insert into county (id, name, district_id) values (15, 'Ovar', 1);
insert into county (id, name, district_id) values (16, 'São João da Madeira', 1);
insert into county (id, name, district_id) values (17, 'Sever do Vouga', 1);
insert into county (id, name, district_id) values (18, 'Vagos', 1);
insert into county (id, name, district_id) values (19, 'Vale de Cambra', 1);
insert into county (id, name, district_id) values (20, 'Aljustrel', 2);
insert into county (id, name, district_id) values (21, 'Almodôvar', 2);
insert into county (id, name, district_id) values (22, 'Alvito', 2);
insert into county (id, name, district_id) values (23, 'Barrancos', 2);
insert into county (id, name, district_id) values (24, 'Beja', 2);
insert into county (id, name, district_id) values (25, 'Castro Verde', 2);
insert into county (id, name, district_id) values (26, 'Cuba', 2);
insert into county (id, name, district_id) values (27, 'Ferreira do Alentejo', 2);
insert into county (id, name, district_id) values (28, 'Mértola', 2);
insert into county (id, name, district_id) values (29, 'Moura', 2);
insert into county (id, name, district_id) values (30, 'Odemira', 2);
insert into county (id, name, district_id) values (31, 'Ourique', 2);
insert into county (id, name, district_id) values (32, 'Serpa', 2);
insert into county (id, name, district_id) values (33, 'Vidigueira', 2);
insert into county (id, name, district_id) values (34, 'Amares', 3);
insert into county (id, name, district_id) values (35, 'Barcelos', 3);
insert into county (id, name, district_id) values (36, 'Braga', 3);
insert into county (id, name, district_id) values (37, 'Cabeceiras de Basto', 3);
insert into county (id, name, district_id) values (38, 'Celorico de Basto', 3);
insert into county (id, name, district_id) values (39, 'Esposende', 3);
insert into county (id, name, district_id) values (40, 'Fafe', 3);
insert into county (id, name, district_id) values (41, 'Guimarães', 3);
insert into county (id, name, district_id) values (42, 'Póvoa de Lanhoso', 3);
insert into county (id, name, district_id) values (43, 'Terras de Bouro', 3);
insert into county (id, name, district_id) values (44, 'Vieira do Minho', 3);
insert into county (id, name, district_id) values (45, 'Vila Nova de Famalicão', 3);
insert into county (id, name, district_id) values (46, 'Vila Verde', 3);
insert into county (id, name, district_id) values (47, 'Vizela', 3);
insert into county (id, name, district_id) values (48, 'Alfândega da Fé', 4);
insert into county (id, name, district_id) values (49, 'Bragança', 4);
insert into county (id, name, district_id) values (50, 'Carrazeda de Ansiães', 4);
insert into county (id, name, district_id) values (51, 'Freixo de Espada à Cinta', 4);
insert into county (id, name, district_id) values (52, 'Macedo de Cavaleiros', 4);
insert into county (id, name, district_id) values (53, 'Miranda do Douro', 4);
insert into county (id, name, district_id) values (54, 'Mirandela', 4);
insert into county (id, name, district_id) values (55, 'Mogadouro', 4);
insert into county (id, name, district_id) values (56, 'Torre de Moncorvo', 4);
insert into county (id, name, district_id) values (57, 'Vila Flor', 4);
insert into county (id, name, district_id) values (58, 'Vimioso', 4);
insert into county (id, name, district_id) values (59, 'Vinhais', 4);
insert into county (id, name, district_id) values (60, 'Belmonte', 5);
insert into county (id, name, district_id) values (61, 'Castelo Branco', 5);
insert into county (id, name, district_id) values (62, 'Covilhã', 5);
insert into county (id, name, district_id) values (63, 'Fundão', 5);
insert into county (id, name, district_id) values (64, 'Idanha-a-Nova', 5);
insert into county (id, name, district_id) values (65, 'Oleiros', 5);
insert into county (id, name, district_id) values (66, 'Penamacor', 5);
insert into county (id, name, district_id) values (67, 'Proença-a-Nova', 5);
insert into county (id, name, district_id) values (68, 'Sertã', 5);
insert into county (id, name, district_id) values (69, 'Vila de Rei', 5);
insert into county (id, name, district_id) values (70, 'Vila Velha de Ródão', 5);
insert into county (id, name, district_id) values (71, 'Arganil', 6);
insert into county (id, name, district_id) values (72, 'Cantanhede', 6);
insert into county (id, name, district_id) values (73, 'Coimbra', 6);
insert into county (id, name, district_id) values (74, 'Condeixa-a-Nova', 6);
insert into county (id, name, district_id) values (75, 'Figueira da Foz', 6);
insert into county (id, name, district_id) values (76, 'Góis', 6);
insert into county (id, name, district_id) values (77, 'Lousã', 6);
insert into county (id, name, district_id) values (78, 'Mira', 6);
insert into county (id, name, district_id) values (79, 'Miranda do Corvo', 6);
insert into county (id, name, district_id) values (80, 'Montemor-o-Velho', 6);
insert into county (id, name, district_id) values (81, 'Oliveira do Hospital', 6);
insert into county (id, name, district_id) values (82, 'Pampilhosa da Serra', 6);
insert into county (id, name, district_id) values (83, 'Penacova', 6);
insert into county (id, name, district_id) values (84, 'Penela', 6);
insert into county (id, name, district_id) values (85, 'Soure', 6);
insert into county (id, name, district_id) values (86, 'Tábua', 6);
insert into county (id, name, district_id) values (87, 'Vila Nova de Poiares', 6);
insert into county (id, name, district_id) values (88, 'Alandroal', 7);
insert into county (id, name, district_id) values (89, 'Arraiolos', 7);
insert into county (id, name, district_id) values (90, 'Borba', 7);
insert into county (id, name, district_id) values (91, 'Estremoz', 7);
insert into county (id, name, district_id) values (92, 'Évora', 7);
insert into county (id, name, district_id) values (93, 'Montemor-o-Novo', 7);
insert into county (id, name, district_id) values (94, 'Mora', 7);
insert into county (id, name, district_id) values (95, 'Mourão', 7);
insert into county (id, name, district_id) values (96, 'Portel', 7);
insert into county (id, name, district_id) values (97, 'Redondo', 7);
insert into county (id, name, district_id) values (98, 'Reguengos de Monsaraz', 7);
insert into county (id, name, district_id) values (99, 'Vendas Novas', 7);
insert into county (id, name, district_id) values (100, 'Viana do Alentejo', 7);
insert into county (id, name, district_id) values (101, 'Vila Viçosa', 7);
insert into county (id, name, district_id) values (102, 'Albufeira', 8);
insert into county (id, name, district_id) values (103, 'Alcoutim', 8);
insert into county (id, name, district_id) values (104, 'Aljezur', 8);
insert into county (id, name, district_id) values (105, 'Castro Marim', 8);
insert into county (id, name, district_id) values (106, 'Faro', 8);
insert into county (id, name, district_id) values (107, 'Lagoa (Algarve)', 8);
insert into county (id, name, district_id) values (108, 'Lagos', 8);
insert into county (id, name, district_id) values (109, 'Loulé', 8);
insert into county (id, name, district_id) values (110, 'Monchique', 8);
insert into county (id, name, district_id) values (111, 'Olhão', 8);
insert into county (id, name, district_id) values (112, 'Portimão', 8);
insert into county (id, name, district_id) values (113, 'São Brás de Alportel', 8);
insert into county (id, name, district_id) values (114, 'Silves', 8);
insert into county (id, name, district_id) values (115, 'Tavira', 8);
insert into county (id, name, district_id) values (116, 'Vila do Bispo', 8);
insert into county (id, name, district_id) values (117, 'Vila Real de Santo António', 8);
insert into county (id, name, district_id) values (118, 'Aguiar da Beira', 9);
insert into county (id, name, district_id) values (119, 'Almeida', 9);
insert into county (id, name, district_id) values (120, 'Celorico da Beira', 9);
insert into county (id, name, district_id) values (121, 'Figueira de Castelo Rodrigo', 9);
insert into county (id, name, district_id) values (122, 'Fornos de Algodres', 9);
insert into county (id, name, district_id) values (123, 'Gouveia', 9);
insert into county (id, name, district_id) values (124, 'Guarda', 9);
insert into county (id, name, district_id) values (125, 'Manteigas', 9);
insert into county (id, name, district_id) values (126, 'Meda', 9);
insert into county (id, name, district_id) values (127, 'Pinhel', 9);
insert into county (id, name, district_id) values (128, 'Sabugal', 9);
insert into county (id, name, district_id) values (129, 'Seia', 9);
insert into county (id, name, district_id) values (130, 'Trancoso', 9);
insert into county (id, name, district_id) values (131, 'Vila Nova de Foz Côa', 9);
insert into county (id, name, district_id) values (132, 'Alcobaça', 10);
insert into county (id, name, district_id) values (133, 'Alvaiázere', 10);
insert into county (id, name, district_id) values (134, 'Ansião', 10);
insert into county (id, name, district_id) values (135, 'Batalha', 10);
insert into county (id, name, district_id) values (136, 'Bombarral', 10);
insert into county (id, name, district_id) values (137, 'Caldas da Rainha', 10);
insert into county (id, name, district_id) values (138, 'Castanheira de Pêra', 10);
insert into county (id, name, district_id) values (139, 'Figueiró dos Vinhos', 10);
insert into county (id, name, district_id) values (140, 'Leiria', 10);
insert into county (id, name, district_id) values (141, 'Marinha Grande', 10);
insert into county (id, name, district_id) values (142, 'Nazaré', 10);
insert into county (id, name, district_id) values (143, 'Óbidos', 10);
insert into county (id, name, district_id) values (144, 'Pedrógão Grande', 10);
insert into county (id, name, district_id) values (145, 'Peniche', 10);
insert into county (id, name, district_id) values (146, 'Pombal', 10);
insert into county (id, name, district_id) values (147, 'Porto de Mós', 10);
insert into county (id, name, district_id) values (148, 'Alenquer', 11);
insert into county (id, name, district_id) values (149, 'Arruda dos Vinhos', 11);
insert into county (id, name, district_id) values (150, 'Azambuja', 11);
insert into county (id, name, district_id) values (151, 'Cadaval', 11);
insert into county (id, name, district_id) values (152, 'Cascais', 11);
insert into county (id, name, district_id) values (153, 'Lisboa', 11);
insert into county (id, name, district_id) values (154, 'Loures', 11);
insert into county (id, name, district_id) values (155, 'Lourinhã', 11);
insert into county (id, name, district_id) values (156, 'Mafra', 11);
insert into county (id, name, district_id) values (157, 'Oeiras', 11);
insert into county (id, name, district_id) values (158, 'Sintra', 11);
insert into county (id, name, district_id) values (159, 'Sobral de Monte Agraço', 11);
insert into county (id, name, district_id) values (160, 'Torres Vedras', 11);
insert into county (id, name, district_id) values (161, 'Vila Franca de Xira', 11);
insert into county (id, name, district_id) values (162, 'Amadora', 11);
insert into county (id, name, district_id) values (163, 'Odivelas', 11);
insert into county (id, name, district_id) values (164, 'Alter do Chão', 12);
insert into county (id, name, district_id) values (165, 'Arronches', 12);
insert into county (id, name, district_id) values (166, 'Avis', 12);
insert into county (id, name, district_id) values (167, 'Campo Maior', 12);
insert into county (id, name, district_id) values (168, 'Castelo de Vide', 12);
insert into county (id, name, district_id) values (169, 'Crato', 12);
insert into county (id, name, district_id) values (170, 'Elvas', 12);
insert into county (id, name, district_id) values (171, 'Fronteira', 12);
insert into county (id, name, district_id) values (172, 'Gavião', 12);
insert into county (id, name, district_id) values (173, 'Marvão', 12);
insert into county (id, name, district_id) values (174, 'Monforte', 12);
insert into county (id, name, district_id) values (175, 'Nisa', 12);
insert into county (id, name, district_id) values (176, 'Ponte de Sor', 12);
insert into county (id, name, district_id) values (177, 'Portalegre', 12);
insert into county (id, name, district_id) values (178, 'Sousel', 12);
insert into county (id, name, district_id) values (179, 'Amarante', 13);
insert into county (id, name, district_id) values (180, 'Baião', 13);
insert into county (id, name, district_id) values (181, 'Felgueiras', 13);
insert into county (id, name, district_id) values (182, 'Gondomar', 13);
insert into county (id, name, district_id) values (183, 'Lousada', 13);
insert into county (id, name, district_id) values (184, 'Maia', 13);
insert into county (id, name, district_id) values (185, 'Marco de Canaveses', 13);
insert into county (id, name, district_id) values (186, 'Matosinhos', 13);
insert into county (id, name, district_id) values (187, 'Paços de Ferreira', 13);
insert into county (id, name, district_id) values (188, 'Paredes', 13);
insert into county (id, name, district_id) values (189, 'Penafiel', 13);
insert into county (id, name, district_id) values (190, 'Porto', 13);
insert into county (id, name, district_id) values (191, 'Póvoa de Varzim', 13);
insert into county (id, name, district_id) values (192, 'Santo Tirso', 13);
insert into county (id, name, district_id) values (193, 'Valongo', 13);
insert into county (id, name, district_id) values (194, 'Vila do Conde', 13);
insert into county (id, name, district_id) values (195, 'Vila Nova de Gaia', 13);
insert into county (id, name, district_id) values (196, 'Trofa', 13);
insert into county (id, name, district_id) values (197, 'Abrantes', 14);
insert into county (id, name, district_id) values (198, 'Alcanena', 14);
insert into county (id, name, district_id) values (199, 'Almeirim', 14);
insert into county (id, name, district_id) values (200, 'Alpiarça', 14);
insert into county (id, name, district_id) values (201, 'Benavente', 14);
insert into county (id, name, district_id) values (202, 'Cartaxo', 14);
insert into county (id, name, district_id) values (203, 'Chamusca', 14);
insert into county (id, name, district_id) values (204, 'Constância', 14);
insert into county (id, name, district_id) values (205, 'Coruche', 14);
insert into county (id, name, district_id) values (206, 'Entroncamento', 14);
insert into county (id, name, district_id) values (207, 'Ferreira do Zêzere', 14);
insert into county (id, name, district_id) values (208, 'Golegã', 14);
insert into county (id, name, district_id) values (209, 'Mação', 14);
insert into county (id, name, district_id) values (210, 'Rio Maior', 14);
insert into county (id, name, district_id) values (211, 'Salvaterra de Magos', 14);
insert into county (id, name, district_id) values (212, 'Santarém', 14);
insert into county (id, name, district_id) values (213, 'Sardoal', 14);
insert into county (id, name, district_id) values (214, 'Tomar', 14);
insert into county (id, name, district_id) values (215, 'Torres Novas', 14);
insert into county (id, name, district_id) values (216, 'Vila Nova da Barquinha', 14);
insert into county (id, name, district_id) values (217, 'Ourém', 14);
insert into county (id, name, district_id) values (218, 'Alcácer do Sal', 15);
insert into county (id, name, district_id) values (219, 'Alcochete', 15);
insert into county (id, name, district_id) values (220, 'Almada', 15);
insert into county (id, name, district_id) values (221, 'Barreiro', 15);
insert into county (id, name, district_id) values (222, 'Grândola', 15);
insert into county (id, name, district_id) values (223, 'Moita', 15);
insert into county (id, name, district_id) values (224, 'Montijo', 15);
insert into county (id, name, district_id) values (225, 'Palmela', 15);
insert into county (id, name, district_id) values (226, 'Santiago do Cacém', 15);
insert into county (id, name, district_id) values (227, 'Seixal', 15);
insert into county (id, name, district_id) values (228, 'Sesimbra', 15);
insert into county (id, name, district_id) values (229, 'Setúbal', 15);
insert into county (id, name, district_id) values (230, 'Sines', 15);
insert into county (id, name, district_id) values (231, 'Arcos de Valdevez', 16);
insert into county (id, name, district_id) values (232, 'Caminha', 16);
insert into county (id, name, district_id) values (233, 'Melgaço', 16);
insert into county (id, name, district_id) values (234, 'Monção', 16);
insert into county (id, name, district_id) values (235, 'Paredes de Coura', 16);
insert into county (id, name, district_id) values (236, 'Ponte da Barca', 16);
insert into county (id, name, district_id) values (237, 'Ponte de Lima', 16);
insert into county (id, name, district_id) values (238, 'Valença', 16);
insert into county (id, name, district_id) values (239, 'Viana do Castelo', 16);
insert into county (id, name, district_id) values (240, 'Vila Nova de Cerveira', 16);
insert into county (id, name, district_id) values (241, 'Alijó', 17);
insert into county (id, name, district_id) values (242, 'Boticas', 17);
insert into county (id, name, district_id) values (243, 'Chaves', 17);
insert into county (id, name, district_id) values (244, 'Mesão Frio', 17);
insert into county (id, name, district_id) values (245, 'Mondim de Basto', 17);
insert into county (id, name, district_id) values (246, 'Montalegre', 17);
insert into county (id, name, district_id) values (247, 'Murça', 17);
insert into county (id, name, district_id) values (248, 'Peso da Régua', 17);
insert into county (id, name, district_id) values (249, 'Ribeira de Pena', 17);
insert into county (id, name, district_id) values (250, 'Sabrosa', 17);
insert into county (id, name, district_id) values (251, 'Santa Marta de Penaguião', 17);
insert into county (id, name, district_id) values (252, 'Valpaços', 17);
insert into county (id, name, district_id) values (253, 'Vila Pouca de Aguiar', 17);
insert into county (id, name, district_id) values (254, 'Vila Real', 17);
insert into county (id, name, district_id) values (255, 'Armamar', 18);
insert into county (id, name, district_id) values (256, 'Carregal do Sal', 18);
insert into county (id, name, district_id) values (257, 'Castro Daire', 18);
insert into county (id, name, district_id) values (258, 'Cinfães', 18);
insert into county (id, name, district_id) values (259, 'Lamego', 18);
insert into county (id, name, district_id) values (260, 'Mangualde', 18);
insert into county (id, name, district_id) values (261, 'Moimenta da Beira', 18);
insert into county (id, name, district_id) values (262, 'Mortágua', 18);
insert into county (id, name, district_id) values (263, 'Nelas', 18);
insert into county (id, name, district_id) values (264, 'Oliveira de Frades', 18);
insert into county (id, name, district_id) values (265, 'Penalva do Castelo', 18);
insert into county (id, name, district_id) values (266, 'Penedono', 18);
insert into county (id, name, district_id) values (267, 'Resende', 18);
insert into county (id, name, district_id) values (268, 'Santa Comba Dão', 18);
insert into county (id, name, district_id) values (269, 'São João da Pesqueira', 18);
insert into county (id, name, district_id) values (270, 'São Pedro do Sul', 18);
insert into county (id, name, district_id) values (271, 'Sátão', 18);
insert into county (id, name, district_id) values (272, 'Sernancelhe', 18);
insert into county (id, name, district_id) values (273, 'Tabuaço', 18);
insert into county (id, name, district_id) values (274, 'Tarouca', 18);
insert into county (id, name, district_id) values (275, 'Tondela', 18);
insert into county (id, name, district_id) values (276, 'Vila Nova de Paiva', 18);
insert into county (id, name, district_id) values (277, 'Viseu', 18);
insert into county (id, name, district_id) values (278, 'Vouzela', 18);